config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/'         => 'pages#index'
  get '/contact'  => 'pages#contact'

  resources :products, only: %i[index show] do
    collection do
      get :cart
      get :checkout
    end
  end

  resources :orders, only: %i[index create]

  root to: redirect('/'), as: 'root'
  
  get '*path'     => 'pages#not_found'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/app_setting.rb
class AppSetting < ApplicationRecord
  mount_uploader :logo, ImageUploader

  def logo_url
    return logo.url unless AppSetting.last.dummy_image

    "/ashion/img/logo.png"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :products, dependent: :destroy

  def image_url
    dummy = AppSetting.last.dummy_image

    return image.url.to_s unless dummy

    "/ashion/img/categories/#{rand(1..5)}.png"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products

  def delivery_status_change
    if delivery == 'not_delivery'
      'delivery'
    elsif delivery == 'delivery'
      'delivery_done'
    end
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  delegate :id, :image, :name, :price, to: :product, allow_nil: true, prefix: true
  delegate :full_name, :phone, :address, :note, to: :order, allow_nil: true, prefix: true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :category

  scope :with_category, -> (category_code = '') { 
    return all if category_code.blank?
    
    joins(:category).where('categories.code = ?', category_code)
   }

  delegate :name, :code, to: :category, prefix: true, allow_nil: true

  def self.search_by(keyword)
    return all if keyword.blank?
  
    where("products.name LIKE :keyword", keyword: "%#{keyword}%")
  end

  def image_url
    dummy = AppSetting.last.dummy_image

    return image.url.to_s unless dummy

    "/ashion/img/shop/shop-#{rand(1..9)}.jpg"
  end

  def discount_price
    return 0 unless discount
    
    total = price - ((discount_percent / 100.0 ) * price)

    total
  end

  def amount
    return discount_price if discount

    price
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def create
    create_order = CreateOrderService.call(params)

    redirect_to orders_path if create_order
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def not_found
    render json: {a: '1'}
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  PER_PAGE = 12

  def index
    @products = Product.search_by(params[:q])
                       .with_category(params[:code])
                       .page(params[:page])
                       .per(PER_PAGE)
  end

  def cart
  end

  def checkout
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_tab(ele_value, current)
    ele_value == current ? "active" : ""
  end

  def app_setting
    AppSetting.first
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_json(product)
    product.slice(:id, :name).merge({
      price: product.amount,
      original_price: product.price.to_f,
      discount: product.discount.to_s,
      image: product.image_url
    })
  end
end

app/views/admin/categories/method_get.html.haml
%h1 hola

app/views/admin/dashboard/_order.html.haml
%div
  %ul
    -Order.order(id: :desc).where(delivery: 'not_delivery').all.map do |order|
      %li
        = link_to(admin_order_path(order)) do
          %h4="#{order.code} - #{order.full_name}"

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .row
      .col-lg-4.col-md-6.col-sm-7
        .footer__about
          .footer__logo
            %a{:href => "./index.html"}
              %img{:alt => "", :src => app_setting.logo_url, width: "#{app_setting.width_logo}px", height: "#{app_setting.height_logo}px" }
          %p=app_setting.description
      .col-lg-2.col-md-3.col-sm-5
        .footer__widget
          %h6 Quick links
          %ul
            %li
              %a{:href => "#"} About
            %li
              %a{:href => "#"} Blogs
            %li
              %a{:href => "#"} Contact
            %li
              %a{:href => "#"} FAQ
      .col-lg-2.col-md-3.col-sm-4
        .footer__widget
          %h6 Account
          %ul
            %li
              %a{:href => "#"} My Account
            %li
              %a{:href => "#"} Orders Tracking
            %li
              %a{:href => "#"} Checkout
            %li
              %a{:href => "#"} Wishlist
      .col-lg-4.col-md-8.col-sm-8
        .footer__newslatter
          %h6 NEWSLETTER
          %form{:action => "#"}
            %input{:placeholder => "Email", :type => "text"}/
            %button.site-btn{:type => "submit"} Subscribe
    .row
      .col-lg-12
        .footer__copyright__text
          %p
            Copyright ©
            :javascript
              document.write(new Date().getFullYear());
            All rights reserved | This template is modify by nguyenthanhcong
            -
            %a{:href => "https://github.com/nguyenthanhcong101096/spa", :target => "_blank"} Github

app/views/layouts/_header.html.haml
- @tab = local_assigns[:tab]

%header.header
  .container-fluid
    .row
      .col-xl-3.col-lg-2
        .header__logo
          %a{:href => "/"}
            %img{:alt => "", :src => app_setting.logo_url, width: "#{app_setting.width_logo}px", height: "#{app_setting.height_logo}px" }/
      .col-xl-6.col-lg-7
        %nav.header__menu
          %ul
            %li{class: current_tab("home", @tab)}
              %a{:href => "/"} Home
            %li{class: current_tab("products", @tab)}
              %a{:href => "/products"} Products
            %li{class: current_tab("cart", @tab)}
              %a{:href => "/products/cart"} Shop Cart
            %li{class: current_tab("contact", @tab)}
              %a{:href => "/contact"} Contact
      .col-lg-3
        .header__right
          %ul.header__right__widget
            %li
              %span.search-switch
                = image_tag("search.png", alt: 'seacrh', width: "20px", height: "20px")
            %li
              %a{:href => "/products/cart"}
                = image_tag("cart.png", alt: 'seacrh', width: "18px", height: "20px")
                .tip.number-cart.hidden 2
    .canvas__open
      =image_tag("/ashion/img/menu.png", height: "20px", width: "20px")

app/views/layouts/_load.html.haml
#preloder
  .loader
.offcanvas-menu-overlay
.offcanvas-menu-wrapper
  .offcanvas__close +
  %ul.offcanvas__widget
    %li
      = image_tag("search.png", alt: 'seacrh', width: "20px", height: "20px", class: 'search-switch')
    %li
      %a{:href => "/products/cart"}
        = image_tag("cart.png", alt: 'seacrh', width: "18px", height: "20px")
        .tip.number-cart.hidden 2
  .offcanvas__logo
    %a{:href => "/"}
      %img{:alt => "", :src => app_setting.logo_url, width: "#{app_setting.width_logo}px", height: "#{app_setting.height_logo}px" }
  #mobile-menu-wrap
  .offcanvas__auth
    %a{:href => "/"} Home
    %a{:href => "/products"} Products
    %a{:href => "/products/cart"} Shop Cart
    %a{:href => "/contact"} Contact

app/views/layouts/_load_js.html.haml
%script{:src => "/ashion/js/jquery-3.3.1.min.js"}
  %script{:src => "/ashion/js/bootstrap.min.js+jquery.magnific-popup.min.js.pagespeed.jc.daGAL4o1Pf.js"}
  %script{:src => "/ashion/js/jquery-ui.min.js"}
  %script{:src => "/ashion/js/mixitup.min.js"}
  %script{:src => "/ashion/js/jquery.countdown.min.js+jquery.slicknav.js+owl.carousel.min.js.pagespeed.jc.18IAooX3Fq.js"}
  %script{:src => "/ashion/js/jquery.nicescroll.min.js"}
  %script{:src => "/ashion/js/main.js"}

app/views/layouts/_search_model.html.haml
.search-model
  .h-100.d-flex.align-items-center.justify-content-center
    .search-close-switch +
    = form_with url: products_path, method: :get, local: { remote: true }, class: "search-model-form" do |f|
      = f.hidden_field :code, value: params[:code] if params.key?(:code)
      %input#search-input.form-control.seach-input{:placeholder => "Search here.....", id: 'q', name: 'q', :type => "text"}/

app/views/layouts/_toast.html.haml
-# .toast1
-#   %h1 AB

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title=app_setting.title
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %link{:href => "/ashion/css/A.bootstrap.min.css+font-awesome.min.css+elegant-icons.css+jquery-ui.min.css+magnific-popup.css+owl.carousel.min.css+slicknav.min.css+style.css,Mcc.TqZU-qSV-1.css.pagespeed.cf.oY1hdioJL9.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap", :rel => "stylesheet"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/load'
    = render 'layouts/header', tab: yield(:tab)
    = render 'layouts/toast'
    = yield
    = render 'layouts/footer'
    = render 'layouts/search_model'
    = render 'layouts/load_js'

app/views/orders/index.html.haml
%section.contact.spad.order-success
  .container
    .row
      .col-lg-4.col-md-4
      .col-lg-4.col-md-4
        .contact__content
          .contact__address
            %h5.u-text-green Create order successfully
      .col-lg-4.col-md-4

app/views/pages/_category.html.haml
.col-lg-6.col-md-6.col-sm-6.p-0
  .categories__item.set-bg{"data-setbg" => category.image_url }
    .categories__text
      %h4=category.name
      %p=category.describe.truncate(100)
      = link_to 'Shop now', products_path(code: category.code)

app/views/pages/_category_large.html.haml
.categories__item.categories__large__item.set-bg{"data-setbg" => category.image_url }
  .categories__text
    %h4=category.name
    %p=category.describe.truncate(100)
    = link_to 'Shop now', products_path(code: category.code)

app/views/pages/_filter_product.html.haml
%section.product.spad
  .container
    .row
      .col-lg-2.col-md-2
        .section-title
          %h4 New product
      .col-lg-10.col-md-10
        %ul.filter__controls
          %li.active{"data-filter" => "*"} All Categories

          - Category.all.each do |cate|
            %li{"data-filter" => ".#{cate.code}"}=cate.name
    .row.property__gallery
      - Category.all.each do |cate|
        =render partial: 'item_filter_product', collection: cate.products.sample(8), as: :product

app/views/pages/_item_filter_product.html.haml
.col-lg-3.col-md-4.col-sm-6.mix{class: "#{product.category.code}"}
  .product__item.sale
    .product__item__pic.set-bg{"data-setbg" => "#{product.image_url}"}
      - if product.discount
        .label.new Disccount
      -# %ul.product__hover
      -#   %li
      -#     %a{class: 'js-add-to-cart','data' => product_json(product)}
      -#       = image_tag("bag.png", alt: 'seacrh', width: "18px", height: "20px")
    .product__item__text
      %h6
        %a{:href => "/products/#{product.id}"}=product.name
      - if product.discount
        .product__price
          =number_to_currency(product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
          %span=number_to_currency(product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
      - else
        .product__price=number_to_currency(product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")

app/views/pages/contact.haml
- content_for(:tab, "contact")

%section.contact.spad
  .container
    .row
      .col-lg-6.col-md-6
        .contact__content
          .contact__address
            %h5 Contact info
            %ul
              %li
                %h6
                  = image_tag("address.png", alt: 'seacrh', width: "15px", height: "20px")
                  Address
                %p=app_setting.address
              %li
                %h6
                  = image_tag("phone.png", alt: 'seacrh', width: "15px", height: "20px")
                  Phone
                %p
                  %span=app_setting.phone
              %li
                %h6
                  = image_tag("payment.png", alt: 'seacrh', width: "15px", height: "15px")
                  Support
                %p=app_setting.email
          .contact__form
            %h5 SEND MESSAGE
            %form{:action => "#"}
              %input{:placeholder => "Name", :type => "text"}/
              %input{:placeholder => "Email", :type => "text"}/
              %textarea{:placeholder => "Message"}
              %button.site-btn{:type => "submit"} Send Message
      .col-lg-6.col-md-6
        .contact__map
          %iframe{:allowfullscreen => "", :height => "780", :src => app_setting.google_map, :style => "border:0"}

app/views/pages/index.html.haml
- content_for(:tab, "home")

%section.categories
  .container-fluid
    .row
      .col-lg-6.p-0
        = render partial: 'category_large', locals: { category: Category.first }
      .col-lg-6
        .row
          = render partial: 'category', collection: Category.last(4), as: :category

= render partial: 'filter_product'

%section.banner.set-bg{"data-setbg" => "/ashion/img/banner/banner-1.jpg"}

-# %section.trend.spad
-#   .container
-#     .row
-#       .col-lg-4.col-md-4.col-sm-6
-#         .trend__content
-#           .section-title
-#             %h4 Hot Trend
-#           .trend__item
-#             .trend__item__pic
-#               %img{:alt => "", :src => "/ashion/img/trend/xht-1.jpg.pagespeed.ic.egi4bL3t5c.webp"}/
-#             .trend__item__text
-#               %h6 Chain bucket bag
-#               .product__price $ 59.0
-#           .trend__item
-#             .trend__item__pic
-#               %img{:alt => "", :src => "/ashion/img/trend/xht-2.jpg.pagespeed.ic.3YjuD2AOub.webp"}/
-#             .trend__item__text
-#               %h6 Pendant earrings
-#               .product__price $ 59.0
-#           .trend__item
-#             .trend__item__pic
-#               %img{:alt => "", :src => "/ashion/img/trend/xht-3.jpg.pagespeed.ic.fw_LsIXAiZ.webp"}/
-#             .trend__item__text
-#               %h6 Cotton T-Shirt
-#               .product__price $ 59.0
-#       .col-lg-4.col-md-4.col-sm-6
-#         .trend__content
-#           .section-title
-#             %h4 Best seller
-#           .trend__item
-#             .trend__item__pic
-#               %img{:alt => "", :src => "/ashion/img/trend/xbs-1.jpg.pagespeed.ic.mJ3HA8np2n.webp"}/
-#             .trend__item__text
-#               %h6 Cotton T-Shirt
-#               .product__price $ 59.0
-#           .trend__item
-#             .trend__item__pic
-#               %img{:alt => "", :src => "/ashion/img/trend/xbs-2.jpg.pagespeed.ic.oPC5eRYONC.webp"}/
-#             .trend__item__text
-#               %h6
-#                 Zip-pockets pebbled tote
-#                 = succeed "briefcase" do
-#                   %br/
-#               .product__price $ 59.0
-#           .trend__item
-#             .trend__item__pic
-#               %img{:alt => "", :src => "/ashion/img/trend/xbs-3.jpg.pagespeed.ic.UbErREAs1-.webp"}/
-#             .trend__item__text
-#               %h6 Round leather bag
-#               .product__price $ 59.0
-#       .col-lg-4.col-md-4.col-sm-6
-#         .trend__content
-#           .section-title
-#             %h4 Feature
-#           .trend__item
-#             .trend__item__pic
-#               %img{:alt => "", :src => "/ashion/img/trend/xf-1.jpg.pagespeed.ic.Q7t675Gcer.webp"}/
-#             .trend__item__text
-#               %h6 Bow wrap skirt
-#               .product__price $ 59.0
-#           .trend__item
-#             .trend__item__pic
-#               %img{:alt => "", :src => "/ashion/img/trend/xf-2.jpg.pagespeed.ic.LE7FQXfxeP.webp"}/
-#             .trend__item__text
-#               %h6 Metallic earrings
-#               .product__price $ 59.0
-#           .trend__item
-#             .trend__item__pic
-#               %img{:alt => "", :src => "/ashion/img/trend/xf-3.jpg.pagespeed.ic.larkQpUfvs.webp"}/
-#             .trend__item__text
-#               %h6 Flap cross-body bag
-#               .product__price $ 59.0
-# %section.services.spad
-#   .container
-#     .row
-#       .col-lg-3.col-md-4.col-sm-6
-#         .services__item
-#           = image_tag("free_ship.png", alt: 'seacrh', width: "41px", height: "36px")
-#           %h6 Free Shipping
-#           %p For all oder over $99
-#       .col-lg-3.col-md-4.col-sm-6
-#         .services__item
-#           = image_tag("money.png", alt: 'seacrh', width: "45px", height: "33px")
-#           %h6 Money Back Guarantee
-#           %p If good have Problems
-#       .col-lg-3.col-md-4.col-sm-6
-#         .services__item
-#           = image_tag("support.png", alt: 'seacrh', width: "40px", height: "40px")
-#           %h6 Online Support 24/7
-#           %p Dedicated support
-#       .col-lg-3.col-md-4.col-sm-6
-#         .services__item
-#           = image_tag("payment.png", alt: 'seacrh', width: "36px", height: "33px")
-#           %h6 Payment Secure
-#           %p 100% secure payment
-# .instagram
-#   .container-fluid
-#     .row
-#       .col-lg-2.col-md-4.col-sm-4.p-0
-#         .instagram__item.set-bg{"data-setbg" => "/ashion/img/instagram/insta-1.jpg"}
-#           .instagram__text
-#             = image_tag("ins.png", alt: 'seacrh', width: "30px", height: "30px")
-#             %a{:href => "#"} @ ashion_shop
-#       .col-lg-2.col-md-4.col-sm-4.p-0
-#         .instagram__item.set-bg{"data-setbg" => "/ashion/img/instagram/insta-2.jpg"}
-#           .instagram__text
-#             = image_tag("ins.png", alt: 'seacrh', width: "30px", height: "30px")
-#             %a{:href => "#"} @ ashion_shop
-#       .col-lg-2.col-md-4.col-sm-4.p-0
-#         .instagram__item.set-bg{"data-setbg" => "/ashion/img/instagram/insta-3.jpg"}
-#           .instagram__text
-#             = image_tag("ins.png", alt: 'seacrh', width: "30px", height: "30px")
-#             %a{:href => "#"} @ ashion_shop
-#       .col-lg-2.col-md-4.col-sm-4.p-0
-#         .instagram__item.set-bg{"data-setbg" => "/ashion/img/instagram/insta-4.jpg"}
-#           .instagram__text
-#             = image_tag("ins.png", alt: 'seacrh', width: "30px", height: "30px")
-#             %a{:href => "#"} @ ashion_shop
-#       .col-lg-2.col-md-4.col-sm-4.p-0
-#         .instagram__item.set-bg{"data-setbg" => "/ashion/img/instagram/insta-5.jpg"}
-#           .instagram__text
-#             = image_tag("ins.png", alt: 'seacrh', width: "30px", height: "30px")
-#             %a{:href => "#"} @ ashion_shop
-#       .col-lg-2.col-md-4.col-sm-4.p-0
-#         .instagram__item.set-bg{"data-setbg" => "/ashion/img/instagram/insta-6.jpg"}
-#           .instagram__text
-#             = image_tag("ins.png", alt: 'seacrh', width: "30px", height: "30px")
-#             %a{:href => "#"} @ ashion_shop

app/views/products/_product.html.haml
.col-lg-4.col-md-6
  .product__item
    .product__item__pic.set-bg{"data-setbg" => "#{product.image_url}"}
      - if product.discount
        .label.new Disccount
      -# %ul.product__hover
      -#   %li
      -#     %a{class: 'js-add-to-cart','data' => product_json(product)}
      -#       = image_tag("bag.png", alt: 'seacrh', width: "18px", height: "20px")
    .product__item__text
      %h6
        %a{:href => "/products/#{product.id}"}=product.name
      - if product.discount
        .product__price
          =number_to_currency(product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
          %span=number_to_currency(product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
      - else
        .product__price=number_to_currency(product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")

app/views/products/_product_relate.html.haml
.col-lg-3.col-md-4.col-sm-6
  .product__item
    .product__item__pic.set-bg{"data-setbg" => "#{product.image_url}"}
      - if product.discount
        .label.new Disccount
      -# %ul.product__hover
      -#   %li
      -#     %a{class: 'js-add-to-cart','data' => product_json(product)}
      -#       = image_tag("bag.png", alt: 'seacrh', width: "18px", height: "20px")
    .product__item__text
      %h6
        %a{:href => "/products/#{product.id}"}=product.name
      - if product.discount
        .product__price
          =number_to_currency(product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
          %span=number_to_currency(product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
      - else
        .product__price=number_to_currency(product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")

app/views/products/cart.html.haml
- content_for(:tab, "cart")

%section.shop-cart.spad
  .container
    .row
      .col-lg-12
        .shop__cart__table
          %table
            %thead
              %tr
                %th Product
                %th Price
                %th Quantity
                %th Total
                %th
            %tbody.js-list-order

    .row
      .col-lg-6.col-md-6.col-sm-6
        .cart__btn
          %a{:href => "/products"} Continue Shopping

    .row
      .col-lg-6
      .col-lg-4.offset-lg-2
        .cart__total__procced
          %h6 Cart total
          %ul
            %li
              Total
              %span.js-total-price $ 750.0
          %a.primary-btn{:href => "/products/checkout"} Proceed to checkout

app/views/products/checkout.html.haml
%section.checkout.spad
  .container
    = form_with(remote: true, url: orders_path, method: 'POST', id: 'createOrderForm', class: 'checkout__form') do |f|
      = f.hidden_field :products
      .row
        .col-lg-8
          %h5 Billing detail
          .row
            .col-lg-12
              .checkout__form__input
                %p
                  Full Name
                  %span *
                = f.text_field :full_name, type: "text", require: true, placeholder: "Please input your name"
            .col-lg-12
              .checkout__form__input
                %p
                  Address
                  %span *
                = f.text_field :address, type: "text", require: true, placeholder: "Please input your address"
            .col-lg-6.col-md-6.col-sm-6
              .checkout__form__input
                %p
                  Phone
                  %span *
                = f.text_field :phone, type: "number", require: true, placeholder: "+84 123456"
            .col-lg-6.col-md-6.col-sm-6.hidden
              .checkout__form__input
                %p
                  Email
                  %span *
                = f.text_field :email, type: "email", require: true
            .col-lg-12
              .checkout__form__input
                %p
                  Oder notes
                  %span *
                = f.text_field :note, type: "text", placeholder: "Note about your order, e.g, special noe for delivery"
        .col-lg-4
          .checkout__order
            %h5 Your order
            .checkout__order__product
              %ul.js-checkout
                %li
                  %span.top__text Product
                  %span.top__text__right Total

            .checkout__order__total
              %ul
                %li
                  Total
                  %span.js-total-price 0 VNĐ
            %button.site-btn.js-create-order Place oder

app/views/products/index.html.haml
- content_for(:tab, "products")

%section.shop.spad
  .container
    .row
      .col-lg-3.col-md-3
        .shop__sidebar
          .sidebar__categories
            .section-title
              %h4 Categories
            .categories__accordion
              #accordionExample.accordion
                .card
                  %h4.categories_text{class: current_tab(nil, params[:code])}=link_to 'All categories', products_path(code: nil)
                - Category.all.each do |cate|
                  .card
                    %h4.categories_text{class: current_tab(cate.code, params[:code])}=link_to cate.name, products_path(code: cate.code)
      .col-lg-9.col-md-9
        .row
          - if @products.any?
            = render partial: 'product', collection: @products, as: :product
          - else
            %h1="Không tìm thấy '#{params[:q]}'"

          .col-lg-12.pagination-box
            = paginate @products

app/views/products/show.html.haml
- content_for(:tab, "products")

%section.product-details.spad
  .container
    .row
      .col-lg-6
        .product__details__pic
          =image_tag(@product.image_url, width: '450px')
      .col-lg-6
        .product__details__text
          %h3
            = @product.name
            %span="Category: #{@product.category_name}"
          .product__details__price
            - if @product.discount
              =number_to_currency(@product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
              %span=number_to_currency(@product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
            - else
              =number_to_currency(@product.amount, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
          %p=@product.description
          .product__details__button
            .quantity
              %span Quantity:
              .pro-qty
                %input.js-quantity{:type => "number", min: "1", max: "5", :value => "1"}/
            %a.cart-btn.js-btn-cart{'data' => product_json(@product), href: "/products/cart"}
              = image_tag("cart2.png", alt: 'seacrh', width: "14px", height: "16px")
              Add to cart
      .col-lg-12
        .product__details__tab
          %ul.nav.nav-tabs{:role => "tablist"}
            %li.nav-item
              %a.nav-link.active{"data-toggle" => "tab", :href => "#tabs-1", :role => "tab"} Description
          .tab-content
            #tabs-1.tab-pane.active{:role => "tabpanel"}
              %h6 Description
              %p=@product.description
    .row
      .col-lg-12.text-center
        .related__title
          %h5 RELATED PRODUCTS
      = render partial: 'product_relate', collection: Product.with_category(@product.category_code).sample(8), as: :product